# Generated by Django 3.2.12 on 2022-03-09 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Place',
            new_name='Places',
        ),
    ]
