# Generated by Django 3.2.12 on 2022-03-10 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0003_details'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='desc',
            new_name='desc2',
        ),
        migrations.RenameField(
            model_name='details',
            old_name='img',
            new_name='img2',
        ),
    ]
