# Generated by Django 3.2.12 on 2022-03-10 14:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0004_auto_20220310_1911'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='name',
            new_name='name2',
        ),
    ]
