# Generated by Django 3.2.12 on 2022-03-11 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exampleapp', '0005_rename_name_details_name2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='details',
            old_name='name2',
            new_name='name',
        ),
    ]
